### ISSUE TITLE
Toggle Welsh

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#159]
## What

Services must provide a Welsh translation/version as a legal requirement. There is inconsistency of how this is done across DWP. 

## Why

Most service seem to provide a text toggle for English/Welsh, but the placement seems to differ, from header bar, just under, in page, to footer.

## Done when

Analysis

- [x] Outreach to design community for examples
- [x] Check other design systems and backlogs for examples
- [x] Collate findings from community and other design systems
- [x] Identify and explore any accessibility requirements and implementation needs
- [x] Speak to Welsh language unit to understand requirements of the Welsh language translation on services
- [x] Find out if there are any technical restraints that could impact services
- [x] Find out what are the business requirements or operational restraints
- [x] Find out legal and compliance requirements and constraints
- [x] Define problem and user needs for design

Governance

- [ ] Review with key stakeholders and make decision on progress of pattern/component
- [ ] Document decision on Design Community Gitlab

Delivery: design, test, build

- [x] Create a prototype/working version of pattern/component
- [x] Review design with Design System team
- [x] Update or create guidance page for use of the pattern/component
- [x] Test prototype with UCD community
- [x] Define what success is for the pattern and document
- [x] Hold content crit on design
- [x] Hold IxD crit on design
- [x] Update design with findings from content and IxD crit
- [x] Final 2i review of guidance page with content design communityDelivery finalised design to front end dev
- [x] ~~Create npm package~~
- [x] Refactor code (if required)
- [x] Run accessibility audit on component
- [x] Identify a service to use pattern/component and work with them to implement with service
- [ ] Agree research plan and feedback timescales for service team implementing the pattern

Governance 

- [x] Review with working group and other key stakeholders and make decision on progress of pattern/component
- [x] Document decision on Design Community Gitlab

Release

- [x] Publish design on design system
- [x] Comms plan out to UCD community
- [ ] Request feedback from UCD community

## Outcomes

A tested and accessible Welsh translation pattern that meets legal requirements. The guidance and code should be easy for services teams to implement and use.

## Who needs to know about this

Welsh language unit
UCD community
Working group
Design System team
Accessibility team

## Related stories

https://github.com/dwp/design-system-community-backlog/issues/26

**Assessibility (Craig's) feedback:**
https://github.com/dwp/design-system/issues/227
(including html feedback and sign off)

**Comment by michaelcattell** [comment]
### Working examples (in outside-of-dwp design systems)

**HMRC:**
https://design.tax.service.gov.uk/hmrc-design-patterns/welsh-language-toggle/

**Land Registry Elements**
http://land-registry-elements.herokuapp.com/language-switcher/demo

**Comment by michaelcattell** [comment]
### Backlog

https://github.com/alphagov/govuk-design-system-backlog/issues/99

**Comment by HelenOsg** [comment]
Welsh language policy https://www.gov.uk/government/organisations/department-for-work-pensions/about/welsh-language-scheme

https://www.gov.uk/service-manual/design/making-your-service-more-inclusive

**Comment by HelenOsg** [comment]
No firm outline on what should be done in a service, other than to allow users to choose Welsh language. This is done different by various services. 
Current conclusion is that we should allow users to switch throughout the service so pattern needs to show the Welsh language selection at the beginning of the service and throughout the service. Placement of this needs reviewing as some services put it at the top of the page and others in the footer.

**Comment by HelenOsg** [comment]
Emailed Alison Dodds in Welsh language unit for advice.

**Comment by HelenOsg** [comment]
Discussion with Alison Dods and Arwel from Welsh Language Unit re:toggle to Welsh.

Legislation and DWP commitment is that all services will be available in Welsh but that's as far as outline goes. UC have a toggle on each page with is the 'Gold Standard' for the requirement.

Key is to move away from hiding the translation in the footer as this is ignored.

UR from HMRC shows that people ignore the footer and like the on page toggle to check their understanding and build confidence (Alison to send over UR)

There is a problem sometimes in the toggle when the backend creates a pdf or something but if it's new service this shouldn't be a problem with new services being developed.

Two stage proposal
1. Include Welsh language translation on the start page of a service
2. Include English/Welsh toggle at the top of each page within a service. The toggle shouldn't change where the user is in the journey, for example it shouldn't send them back to the beginning of the service but keep them on the same page and persist any data they have entered. 

This requirement is linked to other Welsh legislation which is to capture language and contact preferences for those living in Wales. Services should ask users what their language preference is for written and spoken contact, act on this information and record it for future reference.

Next step to mock up designs and guidance (including Craig's accessibility requirements) and send for feedback.

**Comment by jonhurrell** [comment]
Let's check with Budgeting Loans too see what evidence they have to not have the toggle on every page (like it used to).

**Comment by HelenOsg** [comment]
Research from HMR
[HMRC Welsh Language User Report 2020-Final .pdf](https://github.com/dwp/design-system/files/7258366/HMRC.Welsh.Language.User.Report.2020-Final.pdf)
C

**Comment by HelenOsg** [comment]
Suggested page content

Help users to 
Toggle to Welsh

This is currently experimental because more research is needed.

This pattern lets the user change the language used in a service from English to Welsh and from Welsh to English.

Example

When to use

Use the Welsh language toggle when a service is available in Welsh.

When not to use

Do not use the Welsh language toggle when there is no Welsh translation for a service.

How it works

Put the Welsh language toggle on the right hand side below the:
* GOV.UK header
* phase banner


The Welsh language toggle should appear on every page of the service. 
When a user selects the language toggle the page should update to the language selected. 
The user should stay on the same page of the service and not taken back to the beginning of the journey. 


Accessibility requirements

To meet WCAG 2.1 success criterion 3.1.2 ‘Language of parts’  the human language of each part of the page needs to be determined. This helps things like screen readers to pronounce the content correctly.

To meet this requirement the word English needs to have the HTML attribute <html lang="en"> and the word ‘Cymraeg’ needs to have the HTML attribute needs to be <html lang=“cy”>. 

Technical restrictions

If you are unable to present the toggle to welsh on each page of the service you should include a signpost to the Welsh translation on the start page of the service.

Example

This service is also available in Welsh (Cymraeg).

**Comment by michaelcattell** [comment]
Put the content into the branch toggle-welsh, will discuss with Helen what examples to show on page

**Comment by michaelcattell** [comment]
Updated the page with the examples discussed with Helen this morning, but there is some issues with the 1st example (new examples attached)

(this is the 1st example that seemed to be strange - I also included css from HMRC design system for the toggle welsh - https://design.tax.service.gov.uk/hmrc-design-patterns/welsh-language-toggle/#copy)
![image](https://user-images.githubusercontent.com/52162960/135839713-8421f24e-c4d9-4c28-94fc-fbb8d2ac58bb.png)

(2nd example - seems fine!)
![image](https://user-images.githubusercontent.com/52162960/135839863-c5bc169d-a1bb-46a7-81e4-c09c672c7aac.png)

**Comment by simoneduca** [comment]
Couple of things:
1. from the checklist above, I took out "Create npm package" as we don't publish a package for patterns, just for components, same as GDS.
2. The a11y requirements in the page content don't make sense to me. I mean this bit: "the word English needs to have the HTML attribute and the word ‘Cymraeg’ needs to have the HTML attribute needs to be ." Where did the text come from?

**Comment by HelenOsg** [comment]
Thanks Simone. Anything like number 1 that's in the ticket and we dn't need can you remove?

The text came from Craig. I don't 100% understand the requirement so it's hard to get the content right for it. I think it's basically saying they need to have the correct language html tags on them.

**Comment by simoneduca** [comment]
Don't think there's anything else re 1. About 2, sure I understand that, no worries. @abbott567 which html tag did you mean?

**Comment by michaelcattell** [comment]
Alison has replied and has **given the page the ok to go forward**.
"This looks great and will be a good tool for anyone implementing digital services within the Department going forward. "

**Comment by michaelcattell** [comment]
Spacing between "Apply for a benefit" title and edge of black bar background just needs fixing (something around css class container)
![image](https://user-images.githubusercontent.com/52162960/140295137-2f52f22a-816c-4a04-9dd3-15d28dfc967a.png)

**Comment by simoneduca** [comment]
Track progress on [this newer issue](https://github.com/dwp/design-system/issues/159#issuecomment-960613021)

**Comment by martinwake** [comment]
I showed this to the content design community on 26 November 2021. Questions:

- Should the toggle be on the start page AND on every page of the service? The guidance at the moment suggests it is only needed on the start page if it can't be put on every page.
