### ISSUE TITLE
Key details bar

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#161]
## What

The key details bar component displays citizen's identify and important information to a work coach/agent so they know and can check which record they are viewing. We will run a discovery on the use of this component across DWP services.

## Why

The key details bar is used across a number of agent facing services in DWP but there is no clear guidance or best practice and little research on how agents are interacting and using the component. We want to run a discovery on this component to find out more so we can support services currently using it or wanting to use it in the future. This will mean we can put the guidance on the design system site and users can be assured of the quality and usefulness of the component.

## Done when

- [x] Outreach to UCD community for examples and feedback on existing component
- [x] Explore other design systems across government (including backlogs) for examples of similar components
- [x] Define problem and user needs for component
- [x] Find out if there are any technical restraints that could impact services
- [x] Find out what are the business requirements or operational restraints
- [x] Find out legal and compliance requirements and constraints
- [x] Define problem and user needs for design

Governance

- [x] Review with working group and other key stakeholders and make decision on progress of pattern/component
- [x] Document decision on Design Community Gitlab

## Outcomes

A clear knowledge of user needs for this component and a full understanding of the current work and implementation that has been carried out on this component. 

## Who needs to know about this

UCD community
Working group
Design System team
Accessibility team

## Related stories

https://github.com/dwp/design-system-community-backlog/issues/63

**Comment by michaelcattell** [comment]
Updating the visual of the key details bar after discussions with designs and seeing examples on the discussions:
![image](https://user-images.githubusercontent.com/52162960/134003996-6f352ead-8053-47e5-9292-776593332678.png)

@simoneduca to build (shout me if you need help!)

**Comment by martinwake** [comment]
Updated content and pushed to branch for review with @michaelcattell . Needs some work on the "what not to do" examples: we could show images with descriptive ALT text illustrating:
- too many items
- multiple items of the same type in the top block

**Comment by michaelcattell** [comment]
I have questions around flowing of the data points if we have long fields of data, can we stack our data a little nicer?
![image](https://user-images.githubusercontent.com/52162960/140092042-e06f6c30-d531-4413-ae71-a46099a73273.png)
(Jane Doe feels like a bad example as the name is super short)

Also, is the alignment of the tag "complete" correct - it feels like its not inline or has the correct padding all around (the word feels nearer to the bottom than the top - _see the red arrows_) and should the height of the box align to the size of Jane Doe (I believe it does on the DWP examples)- _see the red lines_
![image](https://user-images.githubusercontent.com/52162960/140092746-a7efb60d-1f0f-4535-a1c1-e03529a71dd4.png)

**Comment by michaelcattell** [comment]
Mobile view shows, worth a discussion:
![image](https://user-images.githubusercontent.com/52162960/140291265-1cd4f025-b423-4754-b292-57a3995fe159.png)

**Comment by michaelcattell** [comment]
Questions to answer/ask:
Should the blue bar be full width or not full width of viewpoint
Should the padding on the sides of the bar be inline with the internal header

**Comment by martinwake** [comment]
Accessibility: Craig commented on this at an earlier stage in the community backlog ticket: https://github.com/dwp/design-system-community-backlog/issues/63#issuecomment-761760658. The concern was that the tag is visually similar to a blue-on-white version of the Continue button used in other patterns. 

There is a [relatively active discussion](https://github.com/alphagov/govuk-design-system-backlog/issues/62) on the GOV.UK Design System about the form of the tag component itself. We decided that it would be best to allow the tag component as specified there rather than making a special version of it for DWP.

**Comment by simoneduca** [comment]
Track progress on [this newer issue](https://github.com/dwp/design-system/issues/159#issuecomment-960613021)

**Comment by martinwake** [comment]
I showed this to the Content Design community on 25 November 2021. Questions that came out of the session:

- How would this behave with longer names than "Jane Doe"?
- "Welsh speaker" is on a different line to "Language". Should we avoid field labels and their contents wrapping to different lines?
- Can the bottom block include one or more tag components or is it only for text?

There were several questions about using "flags" within the tag component. 

In the guidance the preferred use of the tag in the top block is for a category that has several possible values. This is different from an optional flag which might or might not appear. We discussed "flags" as things that:

- don't always appear (for example a "high risk" flag on some records but not others)
- aren't mutually exclusive, so their number is unpredictable

If a service has several of these flags, could the design team use the key details bar to show them? If so, how?
