### ISSUE TITLE
Add another thing

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#162]
## What
This pattern lets users enter multiple items of the same type, such as names or addresses.  

## Why
This is a high priority for the interaction design community. There are currently several ways of doing this but there is no clear guidance or best practice and little research on how people are interacting with and using the component. 

## Assumptions
The same pattern can be used across agent-facing and public-facing services.

### Research
- [x] Outreach to UCD community for examples and feedback on existing component
- [x] Explore other design systems across government (including backlogs) for examples of similar components
- [x] #255
    - [x] Clarify relationship to [Add Another in community backlog](https://github.com/dwp/design-system-community-backlog/issues/54) (for NSESA)
    - [x] Find out if there are any technical restraints that could impact services
    - [x] Find out what are the business requirements or operational restraints
    - [x] Find out legal and compliance requirements and constraints
- [x] #256
  
### Design
- [x] #254
    - [x] Work with IxD community to progress draft content
- [x] Feedback from UCD community
- [x] Engage accessibility team for early comments
- [x] Test against user needs, operational needs and technical constraints
- [x] Decide on preferred approach

### Build
- [x] Finalise content
    - [x] Content design crit
    - [x] IxD crit
    - [x] User research input
- [x] #340
- [x] Publish

### Promote
- [ ] Show and tells

### Evolve
- [ ] #331

### Maintain
- [ ] Plan for review
- [ ] Criteria for retirement

## Outcomes
Published guidance on how and when to use this component.

## Who needs to know about this

UCD community
Working group
Design System team
Accessibility team

## Related stories

https://github.com/dwp/design-system-community-backlog/issues/60
https://github.com/dwp/design-system-community-backlog/issues/54

**Comment by jonhurrell** [comment]
Closing this for now as the work stream in the roadmap was meant to reflect the task-list X-Gov effort we are helping with.

**Comment by jonhurrell** [comment]
Meeting to discuss existing designs and implementations on 25th.

**Comment by HelenOsg** [comment]
Simone to find examples of services using the MOJ pattern

**Comment by HelenOsg** [comment]
What are the differences between DWP proposed pattern and MOJ.

**Comment by HelenOsg** [comment]
https://design.homeoffice.gov.uk/patterns/add-multiple-things
