### ISSUE TITLE
Improving the design system site

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#163]
## What

Continually iterate and improve the design system site based on feedback and user needs

## Why

To make sure we are providing a useful and engaging resource for DWP's UCD community we want to improve and iterate the site based on the feedback we received and the user needs we have identified. 

## Done when

- [ ] Confirm high level user needs for design system
- [ ] Analyse design system site against user needs
- [ ] Ask UCD community for feedback on design system
- [ ] Prototype designs against needs and feedback
- [ ] Share designs with UCD community for feedback
- [ ] Publish how to audit patterns or components in your function
- [ ] Create and publish backlog summary page https://github.com/dwp/design-system/issues/104

## Outcomes

A useful resource that is used and improved by the UCD community. 

## Who needs to know about this

Design System team
UCD community
Accessibility team
Working group
