### ISSUE TITLE
Navigation (Primary/Secondary/tabs)

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#176]
## What

Some services, primarily Agent-facing, require navigation as the one page per thing doesn't fit the need or service. Existing assets for navigation exists but updated research is needed and guidance on how to stack/use them together is needed.

## Why

Variation on how this is used across service means there is a lack of consistency.

## Done when

- [ ] Outreach to UCD community for examples and feedback on existing component
- [ ] Explore other design systems across government (including backlogs) for examples of similar components
- [ ] Define problem and user needs for component
- [ ] Find out if there are any technical restraints that could impact services
- [ ] Find out what are the business requirements or operational restraints
- [ ] Find out legal and compliance requirements and constraints
- [ ] Define problem and user needs for design

Governance

- [ ] Review with working group and other key stakeholders and make decision on progress of pattern/component
- [ ] Document decision on Design Community Gitlab

## Outcomes

A clear knowledge of user needs for this component and a full understanding of the current work and implementation that has been carried out on this component. 

## Who needs to know about this

UCD community
Working group
Design System team
Accessibility team

## Related stories
https://github.com/dwp/design-system-community-backlog/issues/25

**Comment by jonhurrell** [comment]
Awaiting on some further examples of the mobile implementation.

**Comment by mitz-lad** [comment]
Review navigation components to draft principles and guidelines when using navigation elements in tandem.

**Comment by mitz-lad** [comment]
Updated the actions on this ticket to reflect our current position and created separate 'child' component tickets. Actions related to design, development and publishing have been moved into the individual tickets for each navigation component.

**Comment by mitz-lad** [comment]
Mocked up approaches for header and side navigation. Currently prioritising publishing of side navigation component before header navigation as the side navigation component has a lower impact than to publish. 

Header navigation will rely on updating the internal service header component and may impact all services currently using it.
