### ISSUE TITLE
Service header

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#177]
## What

A header for internal services

## Why

Ensure consistency and give guidance for designers

## Done when

- [x] Outreach to UCD community for examples and feedback on existing component
- [x] Explore other design systems across government (including backlogs) for examples of similar components
- [x] Define problem and user needs for component
- [x] Find out if there are any technical restraints that could impact services
- [x] Find out what are the business requirements or operational restraints
- [x] Find out legal and compliance requirements and constraints
- [x] Define problem and user needs for design

Governance

- [x] Review with working group and other key stakeholders and make decision on progress of pattern/component
- [x] Document decision on Design Community Gitlab

## Outcomes

A clear knowledge of user needs for this component and a full understanding of the current work and implementation that has been carried out on this component. 

## Who needs to know about this

UCD community
Working group
Design System team
Accessibility team

## Related stories

https://github.com/dwp/design-system-community-backlog/issues/58

**Comment by michaelcattell** [comment]
Content has been updated.

Using design examples as a lead - discussed with Helen and to take this pattern forward we are using two examples:
One example to show without sign in or sign out
![image](https://user-images.githubusercontent.com/52162960/134005037-d1ef2139-2b00-4dbc-bd32-a3e1d82c4e3b.png)

A second example to show with sign out within the design:
![image](https://user-images.githubusercontent.com/52162960/134005117-4100dfa9-fdec-4514-89c1-97612c743478.png)

@simoneduca to code up both (again shout me if you need anything).

On branch: **internal-head**

**Comment by simoneduca** [comment]
Latest fixes:

- [ ]  missing the sign out text on the right side
- [ ] the title hugs the left side of the black bar too when i clicked "show example in new tab"
- [ ] the sub nav link should read "Internal services header"
- [ ] components table internal header link
- [ ] change example title to 'Apply for a benefit'

**Comment by michaelcattell** [comment]
Sign out example:
- The link in the header should be a text link (mentioned on the GDS header example where it shows all items in header are text links) not a button (usual behaviour for buttons is one green button per page to guide the user on what to do next, I don't believe thats the behaviour we want here)
This might also fix the height of the header as it seems a little longer in the "open new example in a tab" version.
- Also, is the padding consistent around the side of the title and link? Looks bigger in the "in page" example, but tighter when opened up in a new tab?

(if needed can provide images/links etc)

**Comment by jonhurrell** [comment]
iframe height. We need to increase the height of the examples to stop the scroll within the example, set a height that accommodates all examples.

**Comment by jonhurrell** [comment]
'open in a new window toolbar' position feels like it's too close and lost. Perhaps we should look to remove the absolute positioning and having it block displayed e.g (note this needs the border removing too).
<img width="1137" alt="Screen Shot 2021-09-24 at 11 17 53" src="https://user-images.githubusercontent.com/809482/134659208-f10fa20b-be5d-4321-8648-8e68b978e28f.png">
:

**Comment by michaelcattell** [comment]
> Sign out example:
> 
> * The link in the header should be a text link (mentioned on the GDS header example where it shows all items in header are text links) not a button (usual behaviour for buttons is one green button per page to guide the user on what to do next, I don't believe thats the behaviour we want here)
>   This might also fix the height of the header as it seems a little longer in the "open new example in a tab" version.
> * Also, is the padding consistent around the side of the title and link? Looks bigger in the "in page" example, but tighter when opened up in a new tab?
> 
> (if needed can provide images/links etc)

Just to update - we discussed this on Friday and agreed to do text link.
