### ISSUE TITLE
Discovery on filters and search component

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#179]
## What

Run a discovery on the Filter and search components

## Why

Research for these components are old and outdated but used across multiple services. A discovery is needed to find out what new work has been done or needs to be done on these components.

## Done when

- [ ] Outreach to UCD community for examples and feedback on existing component
- [ ] Explore other design systems across government (including backlogs) for examples of similar components
- [ ] Define problem and user needs for component
- [ ] Find out if there are any technical restraints that could impact services
- [ ] Find out what are the business requirements or operational restraints
- [ ] Find out legal and compliance requirements and constraints
- [ ] Define problem and user needs for design

Governance

- [ ] Review with working group and other key stakeholders and make decision on progress of pattern/component
- [ ] Document decision on Design Community Gitlab

## Outcomes

A clear knowledge of user needs for this component and a full understanding of the current work and implementation that has been carried out on this component. 

## Who needs to know about this

UCD community
Working group
Design System team
Accessibility team

## Related stories

https://github.com/dwp/design-system-community-backlog/issues/28
https://github.com/dwp/design-system-community-backlog/issues/27

**Comment by srich-DWP** [comment]
Hi are there any examples of a filter design component?

**Comment by simoneduca** [comment]
@srich-DWP I'm currently in the process of building a filter component (halfway there I'd say), so I don't have a live example yet. What do you need it for?

**Comment by srich-DWP** [comment]
Hi @simoneduca I was hoping to add a filter component to my prototype, in essence to filter data on a page. The data is currently displayed in a Timeline view, so I guess there is also a question as to how that would work?
![screencapture-localhost-3000-caseworkers-v3-missed-payments-deo1-details-new-payment-deo-activity-archive-2024-06-19-13_57_18](https://github.com/dwp/design-system/assets/13314733/1f7c7d19-83cd-41b8-a3af-5f096bf4dfa8)
