### ISSUE TITLE
Get started with the design system: how to integrate components with GOVUK Prototype kit and CASA

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#216]
## What
Publish guides on how to integrate (via npm) DWP Design System components when using CASA or the GOVUK prototype kit. Explain how to get them into views.

## Why

Now we have npm modules that can be integrated into builds, let's discuss how to do that.

New services (ARA) are using the CASA framework to build their services. Designers use the GOVUK prototype kit to design their services. Let's make it easier for them to include our components to drive adoption.

Low effort and high impact
Strategic alignment (ARA)

This will meet the follow needs:
- meet people at their tools
- have the latest pattern which is always up to date
- best (accessible) code examples

### For prototype kit / designers (#296)
- [x] Draft guidance (#296)
- [x] Review within team
- [x] Review with users
- [x] Publish
    - [x] #298 
    - [x] #308
    - [x] #284 
- [ ] Notify (from list below)

### For CASA / developers (#297)
- [x] Draft guidance (#297)
- [x] Review within team and with users
- [x] Amends
- [ ] Publish
- [ ] Notify (from list below)

## Outcomes
Drive adoption and use. 

## Who needs to know about this
UCD Community
Greenzone (through more general presentation)

## Related stories
- Add CSS code samples #284 
- Integrate guidance with @benfraserdesign's Training for designers using the Prototype Kit

**Comment by jonhurrell** [comment]
Let's have a thing about where we can embed this guidance inline, e.g: technical guidance.

**Comment by simoneduca** [comment]
General guidance to follow for the article:

1. Install dwp-frontend module.
2. Add module's path to the views configuration.
3.  Add components to views as needed. 
4. Document it.

**Comment by martinwake** [comment]
Workshop with @martinwake @simoneduca and @michaelcattell on 15 November to gather information and start drafting. Main points:
- the main audience will be designers rather than engineers
- we will recommend installing via npm but also make it easier to grab the CSS for individual components, and will explain how to do that properly

Next step is for @martinwake to draft this page for review.

**Comment by martinwake** [comment]
Drafted guidance for designers for review by @simoneduca and @michaelcattell

**Comment by martinwake** [comment]
Rewritten following feedback: next step is to review together.

**Comment by jonhurrell** [comment]
The '[Guidance for using and setting up the Prototype Kit for an Internal Service](https://github.com/dwp/design-system/discussions/347)' needs incorporating into this.
