### ISSUE TITLE
Find my address by postcode/house number

### ISSUE THREAD

**Issue by michaelcattell** [dwp/design-system#237]
This pattern is now published at https://design-system.dwp.gov.uk/patterns/find-an-address

## What
[Original community proposal](https://github.com/dwp/design-system/issues/404#issue-1294229072)

Improve the postcode look up as shown in GDS design system around how we ask users to enter their address using postcode search and associated journeys such as if postcode cannot be found.

## Why
Building on top of the community driven workshop, to document a consistent way to find an address.

- We have existing insights from services to make recommendations here (conditional reveal,  sidebar)
- High effort and impact
- Strategic alignment (ARA)
- High community priority

## Assumptions

We will provide the user with a working pattern to use when postcode/address look up is needed.
Jon Houghton to be the main contact point between the ARA team (those developing) and Design System team (those hosting the guidance) to let us know when work is ready to be received 
ARA to own the research on this and to provide an artefact to help provide assurance to the services using it (that it's been tested)
We will provide examples of the solution within the prototype kit

### Research
- [x] Collate and review existing research
- [x] Run a community-led workshop
- [x] #288

### Design System Build
- [x] Finalise content
    - [x] Content design crit
    - [x] IxD crit
    - [ ] User research input
- [x] #499
- [x] Prototype kit examples
- [x] #500
- [x] Github discussions
- [x] Feedback from operational stakeholders
- [x] Feedback from accessibility team
- [x] Feedback from ARA team to provide on the DS page
- [x] Accessibility audit
- [x] Publish

### Promote
- [ ] Show and tells
- [ ] Github discussions for rolling feedback to show gaps
- [x] Post on slack channels to provide an update of launch

### Maintain
- [ ] Plan for review
- [ ] Review Github discussions
- [ ] Approach GDS design system team

### (Future) Design handover to ARA team
- [x] Collect examples from other services and design systems
- [x] Provide and present the ARA with solutions from the workshop
- [ ] Identify strategic needs and constraints from ARA
- [ ] Identify technical constraints
- [ ] ARA team to test assumptions and feed back to the design system / main point of contact

## Outcomes
- Service teams have clear guidance on how to use this solution
- Users have a consistent experience across services, even when a journey consists of multiple smaller services
- The ARA team have delivered this pattern understanding the feedback and solutions provided
- UR is provided to give assurance to teams
- Working solution within the prototype kit

## Who needs to know about this
UCD community
ARA service teams
Design System team
Accessibility team

## Related stories
Community backlog issue: https://github.com/dwp/design-system/issues/435
DWP Examples (internal access only): https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/132105603170/Enter+address+postcode+look+up
Discussion: 
GDS pattern: https://design-system.service.gov.uk/patterns/addresses/

## Anything else
Maintain a relationship (using main contact point) to ensure delivery and expectations met

**Comment by simoneduca** [comment]
Waiting for feedback from @jon-houghton

**Comment by michaelcattell** [comment]
I've emailed Sarat (who is owning the pattern from handover from Jon Houghton) to keep us in the loop so we can prep for the incoming work from them to document (how to use it, get it working in prototypes, track any insights from use) and add to the design system. as this pattern is in high demand.

**Comment by mitz-lad** [comment]
Design work broken down into sub task #458
