### ISSUE TITLE
Get help with an application or service

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#238]
## What
Guidance on how to show users where they can get support beyond contextual on-page help.

## Why
New services (ARA) are questioning where help information should be placed consistently when users are being moved between microservices (with a footer preference). 

- We have existing insights from services to make recommendations here (conditional reveal, sidebar)
- Medium effort and impact
- Strategic alignment (ARA)

## Assumptions

This is not guidance on contextual, real-time help within a service: for example, recovering from validation errors or help with answering a question in the service. It is specifically about how we should signpost users to help in other channels (if this is available), for example a telephone number or email form.

### Research
- [x] #246
- [x] Collect examples from services and other design systems
- [x] #247
    - [x] Identify user needs
    - [x] Identify strategic needs and constraints from ARA
    - [x] Identify technical constraints
- [x] #250

### Design
- [x] Draft content and sketches for candidate approaches
- [x] Feedback from UCD community
- [ ] Feedback from operational stakeholders
- [x] Feedback from accessibility team
- [x] Test against user needs, operational needs and technical constraints
- [x] Decide on preferred approach

### Build
- [x] Finalise content
    - [x] Content design crit
    - [x] IxD crit
    - [ ] User research input
- [x] Coded examples
- [x] Accessibility audit
     - [x] Actions from accessibility audit
- [x] Publish

### Promote
- [x] Show and tells

### Maintain
- [ ] Plan for review
- [ ] Criteria for retirement

## Outcomes
- Service teams have clear guidance on how to signpost users to external help in other channels
- Users have a consistent experience across services, even when a journey consists of multiple smaller services

## Who needs to know about this
UCD community
ARA service teams
Design System team
Accessibility team

## Related stories
Community backlog issue: https://github.com/dwp/design-system/issues/407
Discussion: https://github.com/dwp/design-system-community-backlog/discussions/73
Ministry of Justice pattern: https://design-patterns.service.justice.gov.uk/patterns/get-help/

## Anything else
[MURAL board from discussion with content designers Oct 21](https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1635171843636/6d57d36f0fcdac13c4d4e7b72e2e87e83829866f?sender=u495afc4d67cf06eb4fbe9889)
There might be more than one appropriate design solution depending on the service. How broad should our guidance be?

**Comment by jonhurrell** [comment]
@dtaylorbrown @simoneduca We need to run through a11y on this.

**Comment by martinwake** [comment]
@martinwake and @mitz-lad reviewed the feedback we've had so far and planned some changes:

- [ ] updating the example to use less content and better represent the normal case that people will encounter
- [ ] adding something (@martinwake ) to highlight that this may not work as well if you have a large amount of content

**Comment by simoneduca** [comment]
Finished all the a11y templates for this.

**Comment by martinwake** [comment]
Also related: signposting BSL users to contact information: https://github.com/dwp/design-system/issues/335
