### ISSUE TITLE
Mobile views in examples

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#241]
## What
Explore ways to make mobile views of our patterns and components more visible in the Design System. 

## Why
A high proportion – perhaps a majority – of customer interactions with DWP online services are on mobile devices. However designers will most often see our coded examples as they would appear on a desktop view. This default extends into design practice within teams, where screenshots and prototypes are usually presented in a desktop view. Making our examples more mobile-focused will bring them closer to the typical user experience.

## Assumptions
- The high proportion of mobile users observed in Universal Credit is also true in other benefit lines and services
- The current responsive coded examples are not meeting this need

### Research
- [ ] Collate and review existing research
- [ ] Get analytics on devices / user agents from as wide a base as possible (Data Analytics / Data Science?)
- [ ] Identify technical constraints
- [ ] Test assumptions
- [ ] Define problem and user needs for design

### Design
- [ ] Collect examples from other services and design systems
- [ ] Draft content and sketches for candidate approaches
- [ ] Feedback from UCD community
- [ ] Feedback from accessibility team
- [ ] Test against user needs, operational needs and technical constraints
- [ ] Decide on preferred approach

### Build
- [ ] Finalise content
    - [ ] Content design crit
    - [ ] IxD crit
    - [ ] User research input
- [ ] Coded examples
- [ ] Accessibility audit
- [ ] Publish

### Promote
- [ ] Show and tells

### Maintain
- [ ] Plan for review
- [ ] Criteria for retirement

## Outcomes
- Mobile views of patterns and components are more prominent in the Design System

## Who needs to know about this
UCD community
Data Analytics
Data Science
Design System team
Accessibility team

## Anything else
- What should our approach be for internal services?

**Comment by martinwake** [comment]
Example of how a viewport toggle might look: 
![image](https://user-images.githubusercontent.com/26182217/165051478-fbdad4d1-5b2c-4900-95db-189efcd6a232.png)
