### ISSUE TITLE
Add another thing

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#242]
## What
This pattern is trying to capture details for multiple items of the same things, for example the need to capture details of a user's job and then ask the user if they have another job - building a picture of multiple jobs/employment. 

It is used on Apply for New Style ESA: replaying the most relevant data field to the theme (in one example the employer name) helped the user identify which job they were giving information about.

Having a replay of the employer questions they have just answered "You've told us about XXXX" helped the user to separate individual job details.

This pattern has been used in a number of question themes within the online form, anywhere where multiple instances of the same thing needed to be captured.

## Why
This is a high priority for the interaction design community. There are currently several ways of doing this and an opportunity to give consistent guidance.

The ['Add to a list' pattern](https://github.com/dwp/design-system-community-backlog/issues/60) doesn't work for this as it's not adding one element but collecting a larger amount of data about a user's employment, such as; employer details, working pattern, any expenses paid and other data attributes. So we needed to have multiple data inputs associated with the job/s and this didn't fit with the existing 'Add to a list' pattern.

## Assumptions
This is different enough from the Add to a list pattern to be useful.

### Research
- [ ] Collate and review existing research
- [ ] Review existing design examples
- [ ] Identify technical constraints
- [ ] Test assumptions
    - [ ] Clarify the different use cases compared to Add to a list
- [ ] Define problem and user needs for design

### Design
- [ ] Collect examples from other services and design systems
- [ ] Draft content and sketches for candidate approaches
- [ ] Feedback from UCD community
- [ ] Feedback from accessibility team
- [ ] Test against user needs, operational needs and technical constraints
- [ ] Decide on preferred approach

### Build
- [ ] Finalise content
    - [ ] Content design crit
    - [ ] IxD crit
    - [ ] User research input
- [ ] Coded examples
- [ ] Accessibility audit
- [ ] Publish

### Promote
- [ ] Show and tells

### Maintain
- [ ] Plan for review
- [ ] Criteria for retirement

## Outcomes
- Designers have clear guidance on how and when to use this pattern

## Who needs to know about this
UCD community
Design System team
Accessibility team

## Related stories
https://github.com/dwp/design-system-community-backlog/issues/54
https://github.com/dwp/design-system-community-backlog/issues/60
https://github.com/dwp/design-system-community-backlog/issues/19

**Comment by martinwake** [comment]
Closing as it's a duplicate of #162
