### ISSUE TITLE
Prototype landing page for version history

### ISSUE THREAD

**Issue by michaelcattell** [dwp/design-system#263]
## What
A page within a prototype that shows past design decisions between branches, versions, UR sessions.

## Why
Brought up within community meetings on how to track design decisions and losing track (miss-comms between change of designers etc).
- High community demand
## Assumptions
A landing page within a prototype might lead to the complete team understanding what the latest is with the prototype
A template will mean we have a structured and consistent way to track decisions for handover

### Research
- [ ] Collate and review existing research
- [ ] Identify strategic needs
- [ ] Identify technical constraints
- [ ] Test assumptions
- [ ] Define problem and user needs for design

### Design
- [ ] Collect examples from other services and design systems
- [ ] Draft content and sketches for candidate approaches
- [ ] Feedback from UCD community
- [ ] Feedback from operational stakeholders
- [ ] Feedback from accessibility team
- [ ] Test against user needs, operational needs and technical constraints
- [ ] Decide on preferred approach

### Build
- [ ] Finalise content
    - [ ] Content design crit
    - [ ] IxD crit
    - [ ] User research input
- [ ] Coded examples
- [ ] Accessibility audit
- [ ] Publish

### Promote
- [ ] Show and tells
- [ ] Update any community tickets 

### Maintain
- [ ] Plan for review
- [ ] Criteria for retirement

## Outcomes
- An agreed design for the landing page
- Teams using it

## Who needs to know about this
UCD community
Design System team
Accessibility team

## Related stories
Discussion: https://github.com/dwp/design-system-community-backlog/discussions/77

## Anything else
Need to reach out within the x-gov community and see if anyone is doing the same
