### ISSUE TITLE
Actions from content audit

### ISSUE THREAD

**Issue by martinwake** [dwp/design-system#350]
## What
Content improvements arising from content audit of the Design System website (#259 )

5 October 2022: Outstanding changes specific to individual patterns and component documentation moved to "Proposed changes" pages on Confluence.

## Global changes

- [x] Add a link to the accessibility manual to every pattern and component. 
- [x] Use the same "Help to improve this" text on every pattern or component - fewer options, as with Add another and Hint text.
- [x] Link to the Service Standard where possible, showing how using these patterns contributes to it. 
These first three are covered by https://github.com/dwp/design-system/issues/412

- [x] #370
- [x] Add Accessibility statement
- [x] #401
- [x] #393
    - [x] correct formatting of footer links
    - [x] remove crown copyright coat of arms (https://dwpdigital.slack.com/archives/CE9MTE4LC/p1644325672573889)
    - [x] review "Other resources" links
- [x] Favicon: doesn't show up in Dark theme in Chrome. Tracked in https://github.com/dwp/design-system/issues/489

## 404 page

- [x] Replace the last line with: “Something broken? Please [raise a new issue on GitHub]( https://github.com/dwp/design-system/issues?q=is%3Aissue+is%3Aopen+label%3A%22%F0%9F%90%9E+bug%22) using the ‘Bug report’ template, or email the design system team on [dwp-design-system@engineering.digital.dwp.gov.uk](mailto:dwp-design-system@engineering.digital.dwp.gov.uk).”
- [x] Include link to a new sitemap page

## Cookies details page
https://design-system.dwp.gov.uk/cookie-details

See [#402 - Update Cookies page]

## Cookie policy
https://design-system.dwp.gov.uk/cookie-policy
See [#402 - Update Cookies page]

## Home
https://design-system.dwp.gov.uk/index

Covered by https://github.com/dwp/design-system/issues/488

- [x] Call to action from tiles: remove "component" or "pattern" from end to make them shorter. 
- [x] Could the tile titles be links?

## Components
https://design-system.dwp.gov.uk/components

- [x] Cut the intro text for length.
- [x] Explain all the labels in one place and use them consistently.
- [x] Do we need a further label for "good to use"? Some users have mentioned this.
- [x] Use the `tag` component for labels in the text so people can recognise them.
- [x] Backlog link – remove the component / pattern distinction and just link to the overall backlog. 

## Timeline
https://design-system.dwp.gov.uk/components/timeline

## Internal services header
https://design-system.dwp.gov.uk/components/internal-services-header

- [x] Services it has been used on – are these public-facing or agent-facing?

## Key details bar
https://design-system.dwp.gov.uk/components/key-details-bar

- [x] In Services using this component: spell out DCAMS.

## Patterns
https://design-system.dwp.gov.uk/patterns

- [x] Move the explanation (to a new page in Get started?) and cut for length. 
- [x] Labels in one place as for components.
- [x] Is a specific backlog link for components useful? It is neat and tidy, but requires people to understand the pattern/component distinction.
- [x] Are there other circumstances in which we might Retire a pattern or component?

## Add another thing
https://design-system.dwp.gov.uk/patterns/add-another-thing

- [x] "Check your answers" page is actually called "Check answers"

## Consent to cookies
https://design-system.dwp.gov.uk/patterns/retired-patterns/consent-to-cookies

- [x] Review in light of queries about format and content specs.

## Make a declaration
https://design-system.dwp.gov.uk/patterns/make-a-declaration

- [x] In “I agree – send my application”, should be an en-rule not a dash.

## Community
https://design-system.dwp.gov.uk/community

- [x] Paragraph break missing.

## Latest updates
https://design-system.dwp.gov.uk/community/latest-updates

- [x] Format: does each entry have a heading and body text? Can they link off to more detailed updates? At the moment they really vary in length and level of detail.
- [x] Include links to new items?
- [x] Date formats are inconsistent: sometimes date, sometimes just month. 
- [x] Is date the most important item? Looks very large

## The team
https://design-system.dwp.gov.uk/community/team

- [x] Replace dashes with en-rules between names and roles

## Backlog 
https://design-system.dwp.gov.uk/community/backlog

- [x] Change “across the DWP” > "across DWP"

## Roadmap
https://design-system.dwp.gov.uk/community/roadmap

- [x] What does the Roadmap link at the end add to this page? Can we do without it?
