### ISSUE TITLE
DWP Pattern for Cookies page

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#356]
## What
The GDS cookies page states 'Work with your organisation’s privacy expert to write the cookies page.'

Our [retired Cookies page pattern](https://design-system.dwp.gov.uk/patterns/retired-patterns/consent-to-cookies) includes some content but it is across two pages and needs editing.

## Why
Let's do this once and re-publish the content for the page type and advice for use with GDS banner component.

## Done when

- [x] Meet with Jane and Jim to discuss immediate need a options for Access to Work
- [x] Discuss content review and explore moving into single page view as per the GDS guidance
- [x] Review with performance and legal team
- [x] Discuss CASA integration

## Related
Discussion on Community backlog: https://github.com/dwp/design-system-community-backlog/discussions/68

**Comment by martinwake** [comment]
Discussed with Jane and Jim on 4 March. Agreed that they would work on using the GOV UK banner component with a single combined cookies page. Things to look out for with this approach include:
- page will be very long, probably making it less likely to be read in full
- positioning of the option to change preferences needs careful thought. At the bottom of the page it is more likely to be missed (especially given that the page is now longer); at the top it comes before the explanation of what you are consenting to.

In the meanwhile the design system team will work on a standard form of words for a single cookies page that:
- is more concise
- works across services
- can be presented for legal approval

**Comment by martinwake** [comment]
Draft standard text for single-page option published to preview branch: needs review by service team and internally in Design Systems team.

**Comment by martinwake** [comment]
Sent for review by service team

**Comment by martinwake** [comment]
Reviewed with the informal working group/service team. Questions that came up:

* doesn't pre-selecting radios on the first visit contradict the rules for the Radio component? We could achieve the same effect by assuming non-consent until the user chooses an option, but not actually setting the radio values.
* the Save and continue method for the primary button (as used in the previous DWP pattern) has been checked for accessibility and seems to have worthwhile advantages over the GOV.UK pattern, which introduces a new element (the green confirm banner on the same page) and a further action for the user (clicking to return). We may want to retain the previous version.

@martinwake will research whether either of these issues has been discussed in the development of the GOVUK pattern and if not, whether we should adopt the changes above rather than following GOVUK precisely.

**Comment by martinwake** [comment]
Asked about pre-selecting radios on the alphagov backlog: https://github.com/alphagov/govuk-design-system-backlog/issues/13#issuecomment-1126128855

**Comment by martinwake** [comment]
Circulated new version for comment and review

**Comment by martinwake** [comment]
Performance analyst confirms version with details components is ready to present to a data protection officer, awaiting content / IxD feedback.

**Comment by martinwake** [comment]
Had feedback from gov.uk design system team on preselecting radios: guidance may be updated to allow this when indicating the current state of a system. We should update our pattern to preselect the "No" option on radios.

**Comment by martinwake** [comment]
Had further content design feedback:

> I’m wondering if we could have an example in the pattern of GA cookies being the only optional cookies? I think [...] Most services only have GA cookies for optional, so I think it would help to have that scenario shown in the pattern.

> I’m still not sure about having the 2 sets of radios, as it does add complexity (and could cause issues with scanning behaviour). It would be good to do some testing of this, as well as the single set of radios for all optional cookies.

**Comment by martinwake** [comment]
Next steps for this pattern:

- [ ] Make version with details component the default in the pattern and the separate page example
- [ ] Consider (also?) presenting an example with GA cookies as the only optional ones, as this is the most common scenario
- [ ] Meet with Jane's team to discuss updates to non-Javascript instructions

@mitz-lad

**Comment by martinwake** [comment]
Requested data protection review and signoff.

**Comment by jonhurrell** [comment]
@martinwake to email Jim.
