### ISSUE TITLE
Internal service footer

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#377]
## What
Guidance on what to display within the footer for an internal service and how that's different to the GOV.UK Design System footer component. This will help to form guidance on designing for internal services.

## Why
Designers are questioning how to customise the GOV.UK footer in the prototype kit, what's appropriate branding and exclusions from the GOV.UK footer

- We have existing research to show the crest is being included in internal service, when (along with the use of Transport typeface) it's part of the GOV.UK brand
- Low effort and medium impact
- Strategic alignment (ARA)

## Assumptions

- We have an assumption (along with the footer working group) that the OGL statement isn't a requirement for non GOV.uk domain services. Working group agreed it was a small risk to exclude this from the design going forward, pending any progress with legal.

### Research
- [x] Collect examples from services
- [x] Discuss existing use case with designers and ways to standardise
- [ ] @martinwake to discuss a potential legal check of the OGL statement inclusion [email sent to try to identify a legal contact to advise on OGL/copyright notices]

### Design
- [x] Design is based on the GOV.UK footer
    - [x] Remove crest and ogl statement

### Build
- [x] Finalise content
    - [x] Content design crit
    - [x] IxD crit
- [x] Coded examples
- [x] Component code
- [x] Preview branch to working group
- [x] Test accessibility
     - [x] Actions from accessibility test
- [x] Cross browser test
     - [x] Actions from browser tests
- [x] Publish
- [x] Publish component to DWP Frontend (NPM)

### Promote and Share
- [x] Preview with footer working group
- [ ] Announce on slack channels
- [ ] Show and tells

### Maintain
- [ ] Plan for review
- [ ] Criteria for retirement

## Outcomes
- Service teams have clear guidance on how to use 
- Designers understand how to use the component in the prototype kit
- Users have a consistent experience across services, even when a journey consists of multiple smaller services

## Who needs to know about this
Footer working group:
- @petejobesdigitaldwp 
- @jon-houghton 
- @htmlandbacon
- Tim Cooper 

UCD community
ARA service teams
Design System team
Accessibility team

## Related stories
- [x] Update guidance on how to include in the prototype kit
- [ ] Update any confluence references with links to component guidance

## Anything else
[Confluence page with examples of how footers are used in DWP services](https://dwpdigital.atlassian.net/wiki/spaces/CDC/pages/132475192372/Footers+in+DWP+online+services)

**Comment by jonhurrell** [comment]
We'll need guidance on how to add back in the 'Clear data' link for prototyping and (if possible) the kit version.

**Comment by martinwake** [comment]
> @martinwake Content tweaks outstanding (outside ticket).

Done on `add-footer` branch
