### ISSUE TITLE
Add community backlog

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#43]
### What work do we need to do?
Create an up-to-date community backlog of components and patterns. 

### Why are we doing it?
There needs to be a single place to discuss, propose, and develop components or patterns.

### How do we know when it’s done?

- [x] Collate all known sources of pattern documentation and discussion
- [x] Run through a hygiene check
- [x] Track and manage request for more information
- [x] Create community backlog in Design System repo #75
- [x] Chunk the work for job family contribution
- [x] Prioritise with the community
