### ISSUE TITLE
Consent to cookies pattern

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#44]
### What work do we need to do?
Help users manage their personal data by telling them what information you store as cookies on their device.

### Why are we doing it?
This will allow public facing services to create cookie tracking consent to gather data insights to improve their services for users. It will allow compliance with the Privacy and Electronic Communications Regulations (“cookie law”).

### Related stories

- [x] Feature: Create routes for the cookie policy and cookie details page [#52](https://github.com/dwp/design-system/issues/52)
- [ ] Feature: Add test to nunjucks components so test spec matches expected output (including any variables)  [#54](https://github.com/dwp/design-system/issues/54)
- [ ] Feature: Bundle static files for cookie banner UI (Nunjucks/SCSS/Tests) via DWP Engineering NPM [#53](https://github.com/dwp/design-system/issues/53)
- [x] Fix: Hide action scripting [#51]([https://github.com/dwp/design-system/issues/51)
- [x] Feature: Add cookies banner UI HTML/Nunjucks code tabs to consent to cookies documentation page [#55](https://github.com/dwp/design-system/issues/55)
- [ ] Feature: Add live demo of consent to cookies to documentation and deprecate the Child Maintenance prototype [#56](https://github.com/dwp/design-system/issues/56)
- [x] Feature: Add a change-log to documentation [#57](https://github.com/dwp/design-system/issues/57)
- [ ] A11y: Arrange accessibility audit with @abbott567 [#58](https://github.com/dwp/design-system/issues/58)
- [ ] Feature: Replace static screenshots with gifs on [#59](https://github.com/dwp/design-system/issues/59)
- [x] Feature: A cookie policy page for the design system and change link in footer [#60](https://github.com/dwp/design-system/issues/60)
- [x] Research: Gather any insights from existing or planned user research [#61](https://github.com/dwp/design-system/issues/61)
- [x] Update cookie pattern page with research and next steps #68
- [ ] Create blog post updating community about work on the cookie consent pattern #70

**Comment by simoneduca** [comment]
New test url https://cookies-consent.design-system.dwp.gov.uk/
