### ISSUE TITLE
Design System communications strategy

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#480]
## What

Create a communications strategy for the design system that outlines our approach to telling people about the work the design system has done. 

The communications strategy will:

- Outline our approach to communications 
- Have clear goals for each communication sent
- State which channels should be used and when
- Detail the groups of people who need to be communicated to
- Outline the type and timing for communications 
- Recommended templates for different types of communications across 

## Why

- Provide a clear and consistent approach to communications
- Make it easy for the design system to send out communications
- Make sure communications are targeted and successful

## Done when

- [x] Communications audit complete https://github.com/dwp/design-system/issues/481
- [x] Test for target communications - key details bar update and consultancy period for pattern https://github.com/dwp/design-system/issues/503
- [x] Mapped out journeys for different types of design system work https://github.com/dwp/design-system/issues/501
- [x] Review work journeys with team
- [x] Create and agree goals for communications https://github.com/dwp/design-system/issues/504
- [x] Document comms channel approach https://github.com/dwp/design-system/issues/505
- [x] Document templates that have been created for Design System communications https://github.com/dwp/design-system/issues/506
- [x] Review the current approach on how updates are shown on the Design System website

## Who needs to know about this
Design system team
Head of interaction
UCD community

**Comment by HelenOsg** [comment]
https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133061017640/Communications+strategy

**Comment by HelenOsg** [comment]
https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133061017640/Communications+strategy

Strategy published on confluence
