### ISSUE TITLE
Navigation: Internal services header navigation

### ISSUE THREAD

**Issue by mitz-lad** [dwp/design-system#496]
## What
**Epic:** [Navigation Components #176](https://github.com/dwp/design-system/issues/176)

Component and associated guidance for internal service header navigation for the purposes of driving consistency within DWP internal services. 

## Why
Some services do not have a persistent global navigation. Where one exists there are multiple executions and versions of a primary/header navigation without definitive research and community consensus. In the absence of this validation the goal of this component is to provide a consistent baseline design for header navigation for services to use and to improve upon. 

## Research
Refer to Epic ticket #176  and [Primary navigation #435](https://github.com/dwp/design-system/issues/435). 

### Design
- [x] [Mock up designs for component #513](https://github.com/dwp/design-system/issues/513)
- [ ] Draft content for guidance https://github.com/dwp/design-system/issues/531 
- [ ] Create GitHub discussion
- [ ] Make preview branch

### Review
- [ ] Accessibility review
- [ ] Working group: request for comments
- [ ] Working group: workshop
- [ ] Community: consultation period
- [ ] Community: IxD show and tell
- [ ] Community: content design show and tell
- [ ] Community: user research show and tell
- [ ] Finalise content

### Build
- [ ] Code example
- [ ] Create website page and update navigation

### Test
- [ ]  # issue number
  - [ ] Write unit tests
  - [ ] [Basic accessibility checks](https://accessibility-manual.dwp.gov.uk/tools-and-resources/basic-accessibility-checks)
  - [ ] [Browser compatibility checks](https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices#test-for-compatibility)
    - [ ] Screenshot evidence for browser design review (confluence)
  - [ ]  [Automated testing](https://accessibility-manual.dwp.gov.uk/tools-and-resources/automated-accessibility-testing)
  - [ ] [Manual testing](https://accessibility-manual.dwp.gov.uk/tools-and-resources/manual-accessibility-testing)
  - [ ] [Assistive technology testing](https://accessibility-manual.dwp.gov.uk/tools-and-resources/assistive-technology-testing)
    - [ ] Complete applicable tests on DAC forms (confluence) 
  - [ ] Send to evidence to a11y team

### Publish
- [ ] Publish to site
- [ ] Show and tells
- [ ] Update any community tickets 
- [ ] Write announcement
- [ ] Set review date

## Outcomes
- Published guidance for service teams on how to use header navigation on internal services
- Users of internal services have a consistent experience using header navigation across services
- Baseline design for header navigation service teams to research and improve upon

## Who needs to know about this
Design System team
UCD community
Accessibility team

## Related stories
- [Navigation Components #176](https://github.com/dwp/design-system/issues/176)
- [Community backlog: Navigation Menu #43](https://github.com/dwp/design-system-community-backlog/issues/43)
- [Primary navigation #435](https://github.com/dwp/design-system/issues/435)
- [Community contribution: Navigation for internal services #453](https://github.com/dwp/design-system/issues/453)

**Comment by mitz-lad** [comment]
Initial designs for header nav component including two variations for handling no-js scenarios ready for reviewing internally with team. 

Initially drafted mock designs and reviewed options with Leah Smith after her workshops on navigation in Health. Picked the strongest implementation  with a view to provide a component to services to allow them to use in testing

Documentation: https://dwpdigital.atlassian.net/wiki/spaces/INTD/pages/133104861339/Design+iterations+Internal+service+header+navigation 
Prototype: https://gitlab.com/dwp/dwp-design-system/design-system-prototypes/-/tree/prototypekit-v13-update
