### ISSUE TITLE
Map out journeys for different types of design system work

### ISSUE THREAD

**Issue by HelenOsg** [dwp/design-system#501]
## What
Map out the journeys for the different types of work that the design system team do

## Why
By mapping out the journeys and stages work goes through we can identify when we need to communicate, to who and through which channels
## Done when
Create journey for 
- [x] New component or pattern
- [x] Update to frontend (fix or accessibility)
- [x] Design system update (new roadmap, new team member, general updates)
- [x] Stakeholder updates
- [x] Presentations/outreach

## Outcomes
Clear understanding of the workflow and communications needs for design system work

## Who needs to know about this
Design system team

## Related stories
https://github.com/dwp/design-system/issues/480

**Comment by HelenOsg** [comment]
https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1664964326699/810fbb6436802ebfd1bc8a7591bf91e36d40f79d?sender=ub9ed1118cc28cdee9b850540
