### ISSUE TITLE
Design System design review

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#546]
## What
Review design system site against our ambitions to be the trusted design resource in the department and a UCD multiplier.

## Why
The site impersonates tenants of other GOV.UK design system, but we have matured past that starting point. We should review it against our own ambitions and expectations, towards a better experience that represents the work that goes into our output.

## Done when

- [x] Outline ambitions and opportunities to make the site better
- [x] Research who's doing it better and why
- [x] Identify key areas (guidance pages) to make improvements the experiences or redefine them
- [x] Create a design brief for @mitz-lad to work against
- [x] Widen the scope of the design system to promote or be home to other overlapping UCD areas (e.g.: service patterns)

## Outcomes
A site that represents our collective expertise in delivery quality design output.

## Who needs to know about this
This will be a team wide inititaive
