### ISSUE TITLE
tech: build out consolidated prototype

### ISSUE THREAD

**Issue by htmlandbacon** [dwp/design-system#658]
## What

Turn the [revisions prototype](https://gitlab.com/dwp/dwp-design-system/dwp-design-system-site-revisions) into a separate [data driven prototype](https://gitlab.com/dwp/dwp-design-system/dwp-design-system-site-revisions-technical).

## Why

Current a lot of the structure of the prototype is repeated, we should make this a data driven approach to align with the main site, utilising layouts, templates, markdown and macros.

### Stage 1 - templates

- [x] start new repo
- - [x]  Build out a section of single depth pages (component)
- - [x] Build out a section of multiple depth pages (pattern)
- - [x] Build out a collection view
- [x] Add markdown render function
- [x] Add additional set of templates to represent each section
- [x] Create a macro to represent top level navigation (v2 - link needed)

### Stage 2 - templates

Following a call with @mitz-lad we agree three broad templates to build out

- [x] [landing page](https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1699976969544/1d753a60ccd9012263a0c95ddf3f194426788229)
- [x] [Content overview](https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1699976969544/1d753a60ccd9012263a0c95ddf3f194426788229?wid=0-1733307273827)
- [x] [multiple item](https://app.mural.co/t/dwpdigital7412/m/dwpdigital7412/1699976969544/1d753a60ccd9012263a0c95ddf3f194426788229?wid=0-1733307284666)

As part of this we will also

- [x] build out full place holder pattern section
- [x] build out a more robust grid system
- [x] clean up patterns overview page
- [x] make some things actual footer nav and remove from global
- [x] apply code samples within a page (i.e guidance)

## Bonus items

- [x] Ability to have a template override driven from the markdown
- [x] Content ordering step

[Task to work out examples](https://github.com/dwp/design-system/issues/650)

## Outcomes

Assumption is we can have data driven prototype that bridges the prototype and main site - we will able to:

- documented groups of content (i.e patterns)
- content in markdown
- macros to represent data points (i.e navigation)
- layouts and templates for each section

## Who needs to know about this

@mitz-lad 
@martinwake
