### ISSUE TITLE
Create Working Group

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#73]
### What work do we need to do?

Create a working group of cross representatives from the department to ensure all components and patterns published in the Design System are of a high quality and meet user need.

The below activity are milestones to reach over the next 6 weeks.
### Why are we doing it?

By including representatives from a mixture of disciplines and departments, the working group helps to ensure that the Design System represents its users.

It means that decisions made are fair and unbiased, and that the Design System reflects the experiences of the whole of government not just one department.

### Related Stories

- [x] Create community backlog in Design System repo #75
- [x] Agree goals for working group
- [x] Get working group members list agreed #76 
- [x] Agree communication channels and plan for working group #77
- [x] Plan first working group meeting #78
- [x] Hold working group meeting 
- [ ] Update community area of design system site with working group information #84
