### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by jonhurrell** [dwp/design-system#99]
## What
A list of actions shown in chronological order. For example, claim history.
## Why
Help users to understand what has happened and when.

## Done when

- [x] Outreach to design community for examples of numbers of items shown in timeline https://github.com/dwp/design-system/issues/131
- [x] Check if guidance is needed for implementation that will affect users or accessibility #133
- [x] Update guidance content following feedback from working group https://github.com/dwp/design-system/issues/120
- [x] Decide if design system needs a tag for agent-facing designs https://github.com/dwp/design-system/issues/128
- [x] Review design of timeline component https://github.com/dwp/design-system/issues/129
- [x] Build timeline page for design system https://github.com/dwp/design-system/issues/130
- [x] Refactor code https://github.com/dwp/design-system/issues/132
- [x] Create npm package
- [x] Identify a service to use component
- [x] Run accessibility audit on component
- [x] Communicate out to UCD community about published pattern and request feedback
- [x] Create research plan

## Who needs to know about this
Jon, Mickey, Helen, Simone
